-- SCHEMA SNAPSHOT — generated by scripts/backup/schema-snapshot.mjs
-- Source: hanapclstjrzzixelmjt.supabase.co   Captured: 2026-08-10T09:17:28.029Z
--
-- Reconstructed from the live database because ten core tables (nodes, workspaces,
-- workspace_members, activities, tasks, lists, chat_threads, notifications, decision_queue,
-- email_connections) were created by hand and never written into a migration.
--
-- Tables are ordered so foreign keys resolve on a top-to-bottom replay into an empty database.
--
-- CAPTURED: columns, types, NOT NULL, primary keys, foreign keys.
-- NOT CAPTURED: indexes, CHECK constraints, defaults, triggers, RLS policies, views.
-- Do NOT run this against production. It is a restore target, not a migration.

create extension if not exists vector;

create table if not exists agent_jobs (
  id uuid not null,
  workspace_id uuid not null,
  agent_name text not null,
  trigger_type text not null,
  status text,
  input jsonb not null,
  output jsonb,
  steps jsonb,
  error text,
  node_ids uuid[],
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone,
  constraint agent_jobs_pkey primary key (id)
);

create table if not exists ai_credits_ledger (
  id uuid not null,
  workspace_id uuid not null,
  amount numeric not null,
  transaction_type text not null,
  description text,
  created_at timestamp with time zone not null,
  constraint ai_credits_ledger_pkey primary key (id)
);

create table if not exists auth_credentials (
  user_id text not null,
  email text not null,
  password_hash text,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  email_verified boolean not null,
  verified_at timestamp with time zone,
  totp_secret text,
  totp_enabled_at timestamp with time zone,
  recovery_codes jsonb,
  google_sub text,
  constraint auth_credentials_pkey primary key (user_id)
);

create table if not exists auth_refresh_tokens (
  id uuid not null,
  user_id text not null,
  token_hash text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null,
  revoked_at timestamp with time zone,
  replaced_by uuid,
  user_agent text,
  ip_address text,
  last_active_at timestamp with time zone,
  constraint auth_refresh_tokens_pkey primary key (id)
);

create table if not exists brain_runs (
  id uuid not null,
  workspace_id text not null,
  mode text not null,
  started_at timestamp with time zone not null,
  finished_at timestamp with time zone,
  status text not null,
  signals_count integer not null,
  proof jsonb not null,
  cost_tokens integer not null,
  error text,
  constraint brain_runs_pkey primary key (id)
);

create table if not exists call_sessions (
  id uuid not null,
  workspace_id uuid not null,
  room text not null,
  initiator_id text not null,
  invitee_id text not null,
  kind text not null,
  status text not null,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  created_at timestamp with time zone not null,
  record boolean not null,
  egress_id text,
  recording_status text,
  recording_url text,
  transcript_status text,
  memory_node_id uuid,
  source text not null,
  origin_filename text,
  duration_sec integer,
  language text,
  consent jsonb,
  retention_until timestamp with time zone,
  constraint call_sessions_pkey primary key (id)
);

create table if not exists call_transcript_lines (
  id uuid not null,
  workspace_id uuid not null,
  room text not null,
  event_id text,
  call_session_id uuid,
  line_id text not null,
  participant_id text,
  speaker_name text not null,
  text text not null,
  lang text,
  ts bigint not null,
  source text not null,
  created_at timestamp with time zone not null,
  constraint call_transcript_lines_pkey primary key (id)
);

create table if not exists caption_translations (
  id uuid not null,
  workspace_id uuid not null,
  text_hash text not null,
  source_lang text not null,
  target_lang text not null,
  translated_text text not null,
  model text,
  created_at timestamp with time zone not null,
  expires_at timestamp with time zone not null,
  constraint caption_translations_pkey primary key (id)
);

create table if not exists chat_groups (
  id uuid not null,
  workspace_id uuid not null,
  name text not null,
  created_by text not null,
  created_at timestamp with time zone not null,
  constraint chat_groups_pkey primary key (id)
);

create table if not exists client_errors (
  fingerprint text not null,
  message text not null,
  source text not null,
  route text,
  occurrences integer not null,
  first_seen_at timestamp with time zone not null,
  last_seen_at timestamp with time zone not null,
  workspace_id uuid,
  release text,
  user_agent text,
  resolved_at timestamp with time zone,
  constraint client_errors_pkey primary key (fingerprint)
);

create table if not exists discovery_cache (
  key text not null,
  kind text not null,
  value jsonb not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null,
  constraint discovery_cache_pkey primary key (key)
);

create table if not exists document_counters (
  workspace_id text not null,
  doc_type text not null,
  next_value bigint not null,
  updated_at timestamp with time zone not null,
  constraint document_counters_pkey primary key (workspace_id, doc_type)
);

create table if not exists fx_rates (
  currency text not null,
  rate numeric not null,
  as_of date not null,
  updated_at timestamp with time zone not null,
  source text not null,
  constraint fx_rates_pkey primary key (currency, as_of)
);

create table if not exists inference_shadow_runs (
  id uuid not null,
  workspace_id text not null,
  created_at timestamp with time zone not null,
  task_class text,
  feature text,
  primary_model text not null,
  primary_latency_ms integer,
  primary_tokens integer,
  primary_chars integer,
  shadow_model text not null,
  shadow_ok boolean not null,
  shadow_latency_ms integer,
  shadow_tokens integer,
  shadow_chars integer,
  similarity_pct integer,
  error text,
  constraint inference_shadow_runs_pkey primary key (id)
);

create table if not exists intelligence_signals (
  id uuid not null,
  workspace_id text not null,
  run_id uuid not null,
  kind text not null,
  severity text not null,
  title text not null,
  detail text not null,
  evidence jsonb not null,
  created_at timestamp with time zone not null,
  constraint intelligence_signals_pkey primary key (id),
  constraint intelligence_signals_run_id_fkey foreign key (run_id) references brain_runs(id)
);

create table if not exists internal_message_thread_state (
  id uuid not null,
  workspace_id uuid not null,
  thread_key text not null,
  user_id text not null,
  archived_at timestamp with time zone,
  last_read_at timestamp with time zone,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint internal_message_thread_state_pkey primary key (id)
);

create table if not exists internal_messages (
  id uuid not null,
  workspace_id uuid not null,
  thread_key text not null,
  sender_id text not null,
  recipient_id text,
  body text not null,
  read_at timestamp with time zone,
  archived_at timestamp with time zone,
  created_at timestamp with time zone not null,
  attachments jsonb not null,
  group_id uuid,
  constraint internal_messages_pkey primary key (id)
);

create table if not exists period_snapshots (
  snapshot_id uuid not null,
  workspace_id text not null,
  period_type text not null,
  period_key text not null,
  period_start timestamp with time zone not null,
  period_end timestamp with time zone not null,
  time_zone text not null,
  week_start smallint not null,
  metrics jsonb not null,
  inputs jsonb not null,
  closed_at timestamp with time zone not null,
  closed_by text not null,
  hash text not null,
  prev_hash text,
  constraint period_snapshots_pkey primary key (snapshot_id)
);

create table if not exists pow_claims (
  id uuid not null,
  user_id text not null,
  challenge_hash text not null,
  nonce text not null,
  context text,
  created_at timestamp with time zone not null,
  constraint pow_claims_pkey primary key (id)
);

create table if not exists project_log (
  id uuid not null,
  kind text not null,
  title text not null,
  detail text,
  category text,
  status text not null,
  sort_order integer not null,
  created_at timestamp with time zone not null,
  completed_at timestamp with time zone,
  constraint project_log_pkey primary key (id)
);

create table if not exists rate_limits (
  key text not null,
  hits integer not null,
  window_start timestamp with time zone not null,
  locked_until timestamp with time zone,
  constraint rate_limits_pkey primary key (key)
);

create table if not exists training_exports (
  id uuid not null,
  example_count integer not null,
  approved_rows integer not null,
  total_tokens integer not null,
  avg_tokens integer not null,
  excluded jsonb not null,
  jsonl text,
  created_at timestamp with time zone not null,
  constraint training_exports_pkey primary key (id)
);

create table if not exists workflow_runs (
  id uuid not null,
  workspace_id uuid not null,
  workflow_id uuid not null,
  record_id uuid,
  trigger_key text not null,
  status text not null,
  actions jsonb not null,
  detail text,
  created_at timestamp with time zone not null,
  constraint workflow_runs_pkey primary key (id)
);

create table if not exists workspace_goals (
  id uuid not null,
  workspace_id text not null,
  scope text not null,
  target_user_id text,
  metric text not null,
  target_value numeric not null,
  window_days integer not null,
  label text,
  created_by text not null,
  created_at timestamp with time zone not null,
  active boolean not null,
  constraint workspace_goals_pkey primary key (id)
);

create table if not exists workspaces (
  id uuid not null,
  name text not null,
  slug text not null,
  logo_url text,
  plan text,
  settings jsonb,
  created_at timestamp with time zone,
  stripe_customer_id text,
  onboarded boolean not null,
  timezone text not null,
  clerk_org_id text,
  deleted_at timestamp with time zone,
  constraint workspaces_pkey primary key (id)
);

create table if not exists ai_feedback (
  id uuid not null,
  workspace_id uuid not null,
  user_id text not null,
  message text not null,
  response text not null,
  rating integer not null,
  thread_id text,
  created_at timestamp with time zone,
  constraint ai_feedback_pkey primary key (id),
  constraint ai_feedback_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists ai_training_logs (
  id uuid not null,
  workspace_id uuid not null,
  agent_name text,
  system_prompt text,
  user_prompt text,
  model_output jsonb,
  user_action text not null,
  edited_output jsonb,
  created_at timestamp with time zone not null,
  constraint ai_training_logs_pkey primary key (id),
  constraint ai_training_logs_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists ai_usage (
  id uuid not null,
  workspace_id uuid not null,
  user_id text not null,
  model text not null,
  message_count integer,
  created_at timestamp with time zone,
  period_start timestamp with time zone not null,
  period_end timestamp with time zone not null,
  prompt_tokens integer not null,
  completion_tokens integer not null,
  total_tokens integer not null,
  feature text,
  task_class text,
  provider text,
  latency_ms integer,
  source_count integer,
  refusal_reason text,
  cache_status text,
  constraint ai_usage_pkey primary key (id),
  constraint ai_usage_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists api_keys (
  id uuid not null,
  workspace_id uuid,
  name text not null,
  key_hash text not null,
  key_prefix text not null,
  created_by text,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone,
  constraint api_keys_pkey primary key (id),
  constraint api_keys_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists chat_group_members (
  group_id uuid not null,
  workspace_id uuid not null,
  user_id text not null,
  added_by text not null,
  added_at timestamp with time zone not null,
  constraint chat_group_members_pkey primary key (group_id, user_id),
  constraint chat_group_members_group_id_fkey foreign key (group_id) references chat_groups(id)
);

create table if not exists chat_threads (
  id uuid not null,
  workspace_id uuid,
  user_id text not null,
  title text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  messages jsonb not null,
  constraint chat_threads_pkey primary key (id),
  constraint chat_threads_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists decision_queue (
  id uuid not null,
  workspace_id uuid not null,
  source_type text not null,
  source_id uuid,
  agent_name text not null,
  title text not null,
  summary text,
  recommended_action text,
  risk_level text,
  confidence numeric,
  evidence jsonb,
  status text not null,
  created_at timestamp with time zone not null,
  resolved_at timestamp with time zone,
  resolved_by text,
  snoozed_until timestamp with time zone,
  generation_context jsonb,
  assignee_id text,
  assignee_email text,
  constraint decision_queue_pkey primary key (id),
  constraint decision_queue_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists discovered_leads (
  id uuid not null,
  workspace_id uuid not null,
  source_url text not null,
  platform text not null,
  author_name text not null,
  raw_content text not null,
  intent_type text not null,
  target_subject text,
  region text,
  confidence_score integer not null,
  created_at timestamp with time zone not null,
  contact jsonb not null,
  fingerprint text,
  constraint discovered_leads_pkey primary key (id),
  constraint discovered_leads_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists email_connections (
  id uuid not null,
  workspace_id uuid,
  user_id text not null,
  provider text not null,
  grant_id text,
  email text not null,
  synced_at timestamp with time zone,
  sync_cursor text,
  created_at timestamp with time zone,
  refresh_token text,
  access_token text,
  token_expiry timestamp with time zone,
  constraint email_connections_pkey primary key (id),
  constraint email_connections_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists lists (
  id uuid not null,
  workspace_id uuid,
  object_type text not null,
  name text not null,
  access_level text,
  owner_id text,
  filters jsonb,
  views jsonb,
  created_at timestamp with time zone,
  visibility text not null,
  shared_with text[],
  constraint lists_pkey primary key (id),
  constraint lists_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists nodes (
  id uuid not null,
  workspace_id uuid not null,
  vertical text not null,
  object_type text not null,
  data jsonb not null,
  embedding vector(1536),
  fts_vector tsvector,
  ai_summary text,
  ai_updated_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  enriched_at timestamp with time zone,
  enrichment_status text,
  relationship_health integer,
  health_updated_at timestamp with time zone,
  health_signals jsonb,
  last_chased_at timestamp with time zone,
  chase_count integer,
  lead_score integer,
  lead_score_updated_at timestamp with time zone,
  lead_score_signals jsonb,
  constraint nodes_pkey primary key (id),
  constraint nodes_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists object_definitions (
  id uuid not null,
  workspace_id uuid,
  vertical text not null,
  slug text not null,
  name_singular text not null,
  name_plural text not null,
  icon text,
  color text,
  is_standard boolean,
  attributes jsonb,
  created_at timestamp with time zone,
  constraint object_definitions_pkey primary key (id),
  constraint object_definitions_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists tags (
  id uuid not null,
  workspace_id uuid not null,
  name text not null,
  color text not null,
  created_at timestamp with time zone,
  constraint tags_pkey primary key (id),
  constraint tags_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists tasks (
  id uuid not null,
  workspace_id uuid not null,
  title text not null,
  completed boolean,
  assignee_id text,
  due_date timestamp with time zone,
  record_id uuid,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  priority text,
  status text,
  notes text,
  assignee_email text,
  labels text[],
  reviewer_id text,
  reviewer_name text,
  reviewed_at timestamp with time zone,
  review_result text,
  overdue_notified_at timestamp with time zone,
  created_by text,
  completed_at timestamp with time zone,
  constraint tasks_pkey primary key (id),
  constraint tasks_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists teams (
  id uuid not null,
  workspace_id uuid,
  name text not null,
  created_at timestamp with time zone,
  constraint teams_pkey primary key (id),
  constraint teams_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists workspace_agent_config (
  id uuid not null,
  workspace_id uuid,
  agent_name text not null,
  enabled boolean,
  config jsonb,
  created_at timestamp with time zone,
  constraint workspace_agent_config_pkey primary key (id),
  constraint workspace_agent_config_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists workspace_invites (
  id uuid not null,
  workspace_id uuid not null,
  email text not null,
  role text not null,
  finance_role text not null,
  invited_by uuid,
  token text not null,
  accepted_at timestamp with time zone,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null,
  module_access jsonb not null,
  constraint workspace_invites_pkey primary key (id),
  constraint workspace_invites_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists workspace_members (
  workspace_id uuid not null,
  user_id text not null,
  role text,
  joined_at timestamp with time zone,
  id uuid,
  email text not null,
  name text not null,
  avatar_url text,
  created_at timestamp with time zone,
  position text,
  finance_role text not null,
  module_access jsonb not null,
  constraint workspace_members_pkey primary key (workspace_id, user_id),
  constraint workspace_members_workspace_id_fkey foreign key (workspace_id) references workspaces(id)
);

create table if not exists activities (
  id uuid not null,
  node_id uuid not null,
  workspace_id uuid not null,
  actor_type text not null,
  actor_id text,
  action text not null,
  diff jsonb,
  ai_summary text,
  metadata jsonb,
  created_at timestamp with time zone,
  constraint activities_pkey primary key (id),
  constraint activities_node_id_fkey foreign key (node_id) references nodes(id)
);

create table if not exists chat_messages (
  id uuid not null,
  thread_id uuid,
  role text,
  content text,
  tool_calls jsonb,
  tool_results jsonb,
  created_at timestamp with time zone,
  constraint chat_messages_pkey primary key (id),
  constraint chat_messages_thread_id_fkey foreign key (thread_id) references chat_threads(id)
);

create table if not exists deal_alerts (
  id uuid not null,
  workspace_id uuid not null,
  node_id uuid not null,
  alert_type text not null,
  days_inactive integer,
  dismissed_at timestamp with time zone,
  created_at timestamp with time zone,
  constraint deal_alerts_pkey primary key (id),
  constraint deal_alerts_workspace_id_fkey foreign key (workspace_id) references workspaces(id),
  constraint deal_alerts_node_id_fkey foreign key (node_id) references nodes(id)
);

create table if not exists decision_comments (
  id uuid not null,
  workspace_id uuid not null,
  decision_id uuid not null,
  author_id text not null,
  author_name text,
  body text not null,
  created_at timestamp with time zone not null,
  constraint decision_comments_pkey primary key (id),
  constraint decision_comments_workspace_id_fkey foreign key (workspace_id) references workspaces(id),
  constraint decision_comments_decision_id_fkey foreign key (decision_id) references decision_queue(id)
);

create table if not exists edges (
  id uuid not null,
  workspace_id uuid not null,
  from_node_id uuid not null,
  to_node_id uuid not null,
  relationship text not null,
  metadata jsonb,
  created_at timestamp with time zone,
  constraint edges_pkey primary key (id),
  constraint edges_workspace_id_fkey foreign key (workspace_id) references workspaces(id),
  constraint edges_from_node_id_fkey foreign key (from_node_id) references nodes(id),
  constraint edges_to_node_id_fkey foreign key (to_node_id) references nodes(id)
);

create table if not exists list_entries (
  id uuid not null,
  list_id uuid,
  node_id uuid,
  position integer,
  entry_data jsonb,
  created_at timestamp with time zone,
  constraint list_entries_pkey primary key (id),
  constraint list_entries_list_id_fkey foreign key (list_id) references lists(id),
  constraint list_entries_node_id_fkey foreign key (node_id) references nodes(id)
);

create table if not exists node_embeddings (
  node_id uuid not null,
  workspace_id uuid not null,
  content text,
  embedding vector(384) not null,
  updated_at timestamp with time zone not null,
  constraint node_embeddings_pkey primary key (node_id),
  constraint node_embeddings_node_id_fkey foreign key (node_id) references nodes(id)
);

create table if not exists node_tags (
  id uuid not null,
  node_id uuid not null,
  tag_id uuid not null,
  workspace_id uuid not null,
  created_at timestamp with time zone,
  constraint node_tags_pkey primary key (id),
  constraint node_tags_node_id_fkey foreign key (node_id) references nodes(id),
  constraint node_tags_tag_id_fkey foreign key (tag_id) references tags(id)
);

create table if not exists notifications (
  id uuid not null,
  workspace_id uuid not null,
  user_id text,
  type text not null,
  message text not null,
  record_name text,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null,
  title text not null,
  body text not null,
  task_id uuid,
  is_read boolean,
  metadata jsonb,
  constraint notifications_pkey primary key (id),
  constraint notifications_workspace_id_fkey foreign key (workspace_id) references workspaces(id),
  constraint notifications_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_activity (
  id uuid not null,
  task_id uuid not null,
  user_id text not null,
  user_name text not null,
  action text not null,
  created_at timestamp with time zone,
  constraint task_activity_pkey primary key (id),
  constraint task_activity_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_assignees (
  id uuid not null,
  task_id uuid not null,
  user_id text not null,
  email text not null,
  name text not null,
  permission text not null,
  created_at timestamp with time zone,
  constraint task_assignees_pkey primary key (id),
  constraint task_assignees_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_attachments (
  id uuid not null,
  task_id uuid not null,
  user_id text not null,
  user_name text not null,
  file_name text not null,
  file_url text not null,
  file_type text not null,
  file_size integer,
  created_at timestamp with time zone,
  name text,
  url text,
  size bigint,
  mime_type text,
  uploaded_by text,
  workspace_id uuid,
  constraint task_attachments_pkey primary key (id),
  constraint task_attachments_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_checklist (
  id uuid not null,
  task_id uuid not null,
  text text not null,
  completed boolean,
  added_by_user_id text not null,
  added_by_name text not null,
  created_at timestamp with time zone,
  constraint task_checklist_pkey primary key (id),
  constraint task_checklist_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_comments (
  id uuid not null,
  task_id uuid not null,
  user_id text not null,
  user_name text not null,
  content text not null,
  created_at timestamp with time zone,
  constraint task_comments_pkey primary key (id),
  constraint task_comments_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_reviews (
  id uuid not null,
  task_id uuid not null,
  round integer not null,
  sent_by_id text not null,
  sent_by_name text not null,
  sent_at timestamp with time zone,
  context text not null,
  reviewer_id text not null,
  reviewer_name text not null,
  action text,
  action_note text,
  action_at timestamp with time zone,
  status text not null,
  constraint task_reviews_pkey primary key (id),
  constraint task_reviews_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists task_views (
  id uuid not null,
  task_id uuid not null,
  user_id text not null,
  user_name text not null,
  viewed_at timestamp with time zone,
  constraint task_views_pkey primary key (id),
  constraint task_views_task_id_fkey foreign key (task_id) references tasks(id)
);

create table if not exists team_members (
  team_id uuid not null,
  user_id text not null,
  constraint team_members_pkey primary key (team_id, user_id),
  constraint team_members_team_id_fkey foreign key (team_id) references teams(id)
);

create table if not exists notification_reads (
  notification_id uuid not null,
  user_id text not null,
  read_at timestamp with time zone not null,
  dismissed boolean not null,
  constraint notification_reads_pkey primary key (notification_id, user_id),
  constraint notification_reads_notification_id_fkey foreign key (notification_id) references notifications(id)
);

create table if not exists task_comment_reactions (
  id uuid not null,
  comment_id uuid not null,
  user_id text not null,
  user_name text not null,
  emoji text not null,
  created_at timestamp with time zone,
  constraint task_comment_reactions_pkey primary key (id),
  constraint task_comment_reactions_comment_id_fkey foreign key (comment_id) references task_comments(id)
);
