import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Columns3, Download, Filter, Grid2X2, ListPlus, MoreHorizontal, Plus, Search, Share2, SlidersHorizontal, SortAsc, Table2, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { EmptyState, PageSkeleton } from "../../../components/ui/page-state";
import { apiClient } from "../../../lib/api-client";

interface NodeRecord { id: string; object_type: string; data: Record<string, unknown>; updated_at: string }
interface ListData { id: string; name: string; object_type: string; access_level: string; entry_count: number }

function display(value: unknown) { return value == null ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value); }

export function ListPage() {
  const { listId = "" } = useParams();
  const navigate = useNavigate();
  const qc = useQueryClient();
  const [view, setView] = useState<"table" | "board">("table");
  const [menuOpen, setMenuOpen] = useState(false);
  const [addOpen, setAddOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [deleteConfirm, setDeleteConfirm] = useState(false);
  const list = useQuery({ queryKey: ["list", listId], queryFn: () => apiClient.get<ListData>(`/lists/${listId}`) });
  const entries = useQuery({ queryKey: ["list-entries", listId], queryFn: () => apiClient.get<NodeRecord[]>(`/lists/${listId}/entries`) });
  const candidates = useQuery({ queryKey: ["list-candidates", list.data?.object_type], queryFn: () => apiClient.get<NodeRecord[]>(`/nodes?object_type=${list.data?.object_type}&limit=50`), enabled: addOpen && Boolean(list.data) });
  const update = useMutation({ mutationFn: (body: Record<string, unknown>) => apiClient.patch(`/lists/${listId}`, body), onSuccess: () => { qc.invalidateQueries({ queryKey: ["list", listId] }); qc.invalidateQueries({ queryKey: ["lists"] }); } });
  const removeList = useMutation({ mutationFn: () => apiClient.delete(`/lists/${listId}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ["lists"] }); navigate("/home"); } });
  const addEntry = useMutation({ mutationFn: (nodeId: string) => apiClient.post(`/lists/${listId}/entries`, { node_id: nodeId }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["list-entries", listId] }); qc.invalidateQueries({ queryKey: ["list", listId] }); setAddOpen(false); } });
  const removeEntry = useMutation({ mutationFn: (nodeId: string) => apiClient.delete(`/lists/${listId}/entries/${nodeId}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ["list-entries", listId] }); qc.invalidateQueries({ queryKey: ["list", listId] }); } });
  const records = entries.data ?? [];
  const columns = useMemo(() => Array.from(new Set(records.flatMap((record) => Object.keys(record.data)))).slice(0, 7), [records]);
  const available = (candidates.data ?? []).filter((record) => !records.some((entry) => entry.id === record.id) && `${record.data.name ?? ""} ${record.data.email ?? ""}`.toLowerCase().includes(search.toLowerCase()));

  function exportCsv() {
    const rows = [columns, ...records.map((record) => columns.map((column) => String(record.data[column] ?? "")))];
    const csv = rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(",")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `${list.data?.name || "list"}.csv`; link.click(); URL.revokeObjectURL(link.href);
  }
  if (list.isLoading) return <div className="p-8"><PageSkeleton rows={7} /></div>;
  if (!list.data) return <div className="grid h-full place-items-center text-sm text-slate-500">List not found.</div>;
  return <div className="px-4 py-6 sm:px-6 sm:py-8">
    <header className="mb-5 flex flex-wrap items-center gap-3"><input value={list.data.name} onChange={(event) => qc.setQueryData(["list", listId], { ...list.data, name: event.target.value })} onBlur={(event) => update.mutate({ name: event.target.value })} className="min-w-0 flex-1 bg-transparent text-xl font-semibold outline-none" /><span className="rounded-full border border-white/10 px-2.5 py-1 text-xs capitalize text-slate-500">{list.data.object_type}</span><div className="flex rounded-md border border-white/10 p-1"><button title="Table view" onClick={() => setView("table")} className={`grid h-7 w-7 place-items-center rounded ${view === "table" ? "bg-white/10" : "text-slate-600"}`}><Table2 size={13} /></button><button title="Board view" onClick={() => setView("board")} className={`grid h-7 w-7 place-items-center rounded ${view === "board" ? "bg-white/10" : "text-slate-600"}`}><Grid2X2 size={13} /></button></div></header>
    <div className="mb-5 flex flex-wrap items-center gap-2"><button onClick={() => setAddOpen(true)} className="flex h-9 items-center gap-2 rounded-md bg-red-600 px-3 text-sm"><Plus size={14} /> Add record</button>{[[Filter, "Filter"], [SortAsc, "Sort"], [Columns3, "Group by"], [SlidersHorizontal, "Fields"], [Share2, "Share"]].map(([Icon, label]) => { const Component = Icon as typeof Filter; return <button key={label as string} className="flex h-9 items-center gap-2 rounded-md border border-white/10 px-3 text-sm text-slate-400"><Component size={13} /> {label as string}</button>; })}<div className="relative ml-auto"><button onClick={() => setMenuOpen(!menuOpen)} title="List menu" className="grid h-9 w-9 place-items-center rounded-md border border-white/10"><MoreHorizontal size={15} /></button>{menuOpen ? <div className="absolute right-0 z-20 mt-1 w-44 rounded-md border border-white/10 bg-[#15181d] p-1 shadow-xl"><button onClick={() => { const name = window.prompt("Rename list", list.data?.name); if (name) update.mutate({ name }); }} className="w-full rounded px-3 py-2 text-left text-sm hover:bg-white/[.05]">Rename</button><button onClick={() => apiClient.post("/lists", { name: `${list.data?.name} copy`, object_type: list.data?.object_type })} className="w-full rounded px-3 py-2 text-left text-sm hover:bg-white/[.05]">Duplicate</button><button className="w-full rounded px-3 py-2 text-left text-sm hover:bg-white/[.05]">Share</button><button onClick={exportCsv} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-white/[.05]"><Download size={13} /> Export CSV</button><button onClick={() => setDeleteConfirm(true)} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm text-red-400 hover:bg-red-500/10"><Trash2 size={13} /> Delete</button></div> : null}</div></div>
    {entries.isLoading ? <PageSkeleton rows={6} /> : records.length === 0 ? <EmptyState icon={ListPlus} title="No records in this list yet" description="Add an existing record or create a new one." action={<button onClick={() => setAddOpen(true)} className="rounded-md bg-red-600 px-3 py-2 text-sm">Add record</button>} /> : view === "table" ? <div className="overflow-auto rounded-lg border border-white/10"><table className="min-w-full text-left text-sm"><thead className="bg-white/[.025] text-xs capitalize text-slate-500"><tr>{columns.map((column) => <th key={column} className="px-4 py-3">{column.replaceAll("_", " ")}</th>)}<th className="px-4">Updated</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} onContextMenu={(event) => { event.preventDefault(); if (window.confirm("Remove this record from the list?")) removeEntry.mutate(record.id); }} className="border-t border-white/10 hover:bg-white/[.025]">{columns.map((column, index) => <td key={column} className="max-w-72 truncate px-4 py-3">{index === 0 ? <Link to={`/objects/${record.object_type}/${record.id}`} className="font-medium hover:text-red-400">{display(record.data[column])}</Link> : display(record.data[column])}</td>)}<td className="px-4 text-xs text-slate-600">{new Date(record.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <div className="grid gap-4 md:grid-cols-3">{["Unassigned", "Active", "Complete"].map((stage) => <section key={stage} className="rounded-lg bg-white/[.02] p-3"><h2 className="mb-3 text-xs font-semibold uppercase text-slate-600">{stage}</h2><div className="space-y-2">{records.filter((record) => stage === "Unassigned" ? !record.data.stage : String(record.data.stage ?? "").toLowerCase().includes(stage.toLowerCase())).map((record) => <Link key={record.id} to={`/objects/${record.object_type}/${record.id}`} className="block rounded-md border border-white/10 bg-[#0d1014] p-3"><p className="truncate text-sm font-medium">{String(record.data.name ?? record.data.title ?? "Untitled")}</p><p className="mt-2 truncate text-xs text-slate-600">{String(record.data.company ?? record.data.email ?? "")}</p></Link>)}</div></section>)}</div>}
    {addOpen ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-lg border border-white/10 bg-[#111419] p-5"><div className="flex items-center justify-between"><h2 className="font-medium">Add record</h2><button onClick={() => setAddOpen(false)}><X size={16} /></button></div><label className="relative mt-4 block"><Search className="absolute left-3 top-2.5 text-slate-600" size={14} /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} className="h-9 w-full rounded-md border border-white/10 bg-transparent pl-9 pr-3 text-sm" placeholder="Search existing records" /></label><div className="mt-3 max-h-72 overflow-auto">{available.map((record) => <button key={record.id} onClick={() => addEntry.mutate(record.id)} className="flex w-full items-center justify-between border-b border-white/10 p-3 text-left hover:bg-white/[.03]"><div><p className="text-sm">{String(record.data.name ?? record.data.title ?? "Untitled")}</p><p className="text-xs text-slate-600">{String(record.data.email ?? record.data.company ?? "")}</p></div><Plus size={14} /></button>)}</div><Link to={`/objects/${list.data.object_type}`} className="mt-4 block border-t border-white/10 pt-4 text-sm text-red-400">Create new record</Link></div></div> : null}
    {deleteConfirm ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-sm rounded-lg border border-white/10 bg-[#111419] p-5"><h2 className="font-medium">Delete this list?</h2><p className="mt-2 text-sm text-slate-500">Records will not be deleted.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setDeleteConfirm(false)} className="px-3 py-2 text-sm">Cancel</button><button onClick={() => removeList.mutate()} className="rounded-md bg-red-600 px-3 py-2 text-sm">Delete list</button></div></div></div> : null}
  </div>;
}
